# remote control:
# start control: LT + START
# stop control: LT + A + B
# Ready position: LB
# Zero position: RB


robot_bridge:
  ros__parameters:
    robot_name: "T1"
    duration: 2.0
    control_dt: 0.002
    empty_joint_index: -1
    num_joint: 23
    torque_control: false

    upper_limbs_kp_min: 0.0
    upper_limbs_kp_max: 5000.0
    upper_limbs_kd_min: 0.0
    upper_limbs_kd_max: 5000.0

    lower_limbs_kp_min: 0.0
    lower_limbs_kp_max: 5000.0
    lower_limbs_kd_min: 0.0
    lower_limbs_kd_max: 5000.0

    joint_names: ["HeadYaw", "HeadPitch", 
                  "LeftShoulderPitch", "LeftShoulderRoll", "LeftShoulderYaw", "LeftElbow",
                  "RightShoulderPitch", "RightShoulderRoll", "RightShoulderYaw", "RightElbow",
                  "WaistYaw",
                  "LeftHipPitch", "LeftHipRoll", "LeftHipYaw", "LeftKnee", "LeftAnkleUp", "LeftAnkleDown",
                  "RightHipPitch", "RightHipRoll", "RightHipYaw", "RightKnee","RightAnkleUp", "RightAnkleDown"]

    ready_q: [0.0, 0.0, 
                0.2, -1.35, 0.0, -0.5,
                0.2, 1.35, 0.0, 0.5,
                0.0,
                -0.2, 0.0, 0.0, 0.4, -0.25, 0.0,
                -0.2, 0.0, 0.0, 0.4, -0.25, 0.0]

    # ready_q: [0.0, 0.0, 
    #           0.0, -1.3, 0.0, -1.5,
    #           0.0, 1.3, 0.0, 1.5,
    #           0.0,
    #           0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
    #           0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
              
    HeadYaw:
      idx: 0
      q_min: -1.012
      q_max: 1.012
      dq_limit: 12.56
      tau_limit: 7.0
      kp: 5.0
      kd: 0.1
      if_strong_joint: false

    HeadPitch:
      idx: 1
      q_min: -0.314
      q_max: 0.820
      dq_limit: 12.56
      tau_limit: 7.0      
      kp: 5.0
      kd: 0.1
      if_strong_joint: false

    LeftShoulderPitch:
      idx: 2
      q_min: -3.281
      q_max: 1.187
      dq_limit: 18.84
      tau_limit: 10.0      
      kp: 40.0
      kd: 0.5
      if_strong_joint: false

    LeftShoulderRoll:
      idx: 3
      q_min: -1.640
      q_max: 1.536
      dq_limit: 18.84
      tau_limit: 10.0      
      kp: 50.0
      kd: 1.5
      if_strong_joint: false

    LeftShoulderYaw:
      idx: 4
      q_min: -2.234
      q_max: 2.234
      dq_limit: 18.84
      tau_limit: 10.0      
      kp: 20.0
      kd: 0.2
      if_strong_joint: false

    LeftElbow:
      idx: 5
      q_min: -2.094
      q_max: 0.035
      dq_limit: 18.84
      tau_limit: 10.0
      kp: 10.0
      kd: 0.2
      if_strong_joint: false

    RightShoulderPitch:
      idx: 6
      q_min: -3.281
      q_max: 1.187
      dq_limit: 18.84
      tau_limit: 10.0      
      kp: 40.0
      kd: 0.5
      if_strong_joint: false

    RightShoulderRoll:
      idx: 7
      q_min: -1.536
      q_max: 1.640
      dq_limit: 18.84
      tau_limit: 10.0
      kp: 50.0
      kd: 1.5
      if_strong_joint: false

    RightShoulderYaw:
      idx: 8
      q_min: -2.234
      q_max: 2.234
      dq_limit: 18.84
      tau_limit: 10.0
      kp: 20.0
      kd: 0.2
      if_strong_joint: false

    RightElbow:
      idx: 9
      q_min: 0.000
      q_max: 2.094
      dq_limit: 18.84
      tau_limit: 10.0
      kp: 10.0
      kd: 0.2 
      if_strong_joint: false

    WaistYaw:  
      idx: 10
      q_min: -1.012
      q_max: 1.012
      dq_limit: 10.88
      tau_limit: 30.0      
      kp: 100.0
      kd: 5.0
      if_strong_joint: true

    LeftHipPitch:
      idx: 11
      q_min: -2.059
      q_max: 2.059
      dq_limit: 12.5
      tau_limit: 60.0      
      kp: 350.0
      kd: 7.5
      if_strong_joint: true

    LeftHipRoll:  
      idx: 12
      q_min: -0.366
      q_max: 1.536
      dq_limit: 10.9
      tau_limit: 25.0      
      kp: 350.0
      kd: 7.5
      if_strong_joint: true

    LeftHipYaw: 
      idx: 13
      q_min: -1.012
      q_max: 1.012
      dq_limit: 10.9
      tau_limit: 30.0      
      kp: 180.0
      kd: 3.0
      if_strong_joint: true

    LeftKnee:
      idx: 14
      q_min: 0.000
      q_max: 2.146
      dq_limit: 11.7
      tau_limit: 60.0
      kp: 350.0
      kd: 5.5
      if_strong_joint: true

    LeftAnkleUp:
      idx: 15
      q_min: -0.401
      q_max: 0.855
      dq_limit: 18.8
      tau_limit: 24.0      
      kp: 400.0
      kd: 0.5
      if_strong_joint: false
    
    LeftAnkleDown:
      idx: 16
      q_min: -0.419
      q_max: 0.785
      dq_limit: 12.4
      tau_limit: 15.0      
      kp: 400.0
      kd: 0.5
      if_strong_joint: false 
    
    RightHipPitch:
      idx: 17
      q_min: -2.059
      q_max: 2.059
      dq_limit: 12.5
      tau_limit: 60.0     
      kp: 350.0
      kd: 7.5
      if_strong_joint: true
    
    RightHipRoll:
      idx: 18   
      q_min: -1.536
      q_max: 0.366
      dq_limit: 10.9  
      tau_limit: 25.0
      kp: 350.0
      kd: 7.5
      if_strong_joint: true

    RightHipYaw:
      idx: 19
      q_min: -1.012
      q_max: 1.012
      dq_limit: 10.9
      tau_limit: 30.0      
      kp: 180.0
      kd: 3.0
      if_strong_joint: true

    RightKnee:
      idx: 20
      q_min: -0.192
      q_max: 2.146
      dq_limit: 11.7
      tau_limit: 60.0  
      kp: 350.0
      kd: 5.5
      if_strong_joint: true

    RightAnkleUp:
      idx: 21
      q_min: -0.401
      q_max: 0.855
      dq_limit: 18.8
      tau_limit: 24.0      
      kp: 400.0
      kd: 0.5 
      if_strong_joint: false
    
    RightAnkleDown:
      idx: 22
      q_min: -0.419      
      q_max: 0.785
      dq_limit: 12.4
      tau_limit: 15.0  
      kp: 400.0
      kd: 0.5 
      if_strong_joint: false
